added buttons for title and subtitle, added icons for bold, italic and underline
qmfkdldks/vivid-editor pull request #27
Opened 2020-09-07 15:53 UTC by i-fer

… props. Style.js: added styled icons for bold, italic and underline. Changed from a to button on styles component

__ISSUE_REF__

### Issue

added icons an buttons for title, subtitle, added icons for bold, icon and underline

### Acceptance Criteria

user is able to see buttons on the toolbar

### Screenshots

### QA Steps

_Give a brief list of steps to QA the changes in this PR._

2020-09-07 18:36 UTC, qmfkdldks requested changes
Can you run these commands and resolve all issues (tests and lint)?
And does mark buttons work as expected?

```shell
git checkout master
git pull origin master
git checkout adding-sneak-animation
git rebase master

yarn test
yarn test:lint
```

2020-09-07 18:36 UTC, qmfkdldks commented on src/style.js
> +export const BoldIcon = styled(Bold)`
Great! :+1:

2020-09-07 18:36 UTC, qmfkdldks commented on src/editor.js
> +        <MarkButton format="code">
I think format should be underline instead of the code.

2020-09-09 18:12 UTC, i-fer commented
> Can you run these commands and resolve all issues (tests and lint)?
> And does mark buttons work as expected?
> 
> ```shell
> git checkout master
> git pull origin master
> git checkout adding-sneak-animation
> git rebase master
> 
> yarn test
> yarn test:lint
> ```


where it says "git checkout adding-sneak-animation" should it be "git checkout add  addToolbarButtons"  ?

2020-09-11 20:12 UTC, qmfkdldks commented
> > Can you run these commands and resolve all issues (tests and lint)?
> > And does mark buttons work as expected?
> > ```shell
> > git checkout master
> > git pull origin master
> > git checkout adding-sneak-animation
> > git rebase master
> > 
> > yarn test
> > yarn test:lint
> > ```
> 
> where it says "git checkout adding-sneak-animation" should it be "git checkout add addToolbarButtons" ?

You are right. Can you rebase from master and fix all lint issues?

> > Can you run these commands and resolve all issues (tests and lint)?
> > And does mark buttons work as expected?
> > ```shell
> > git checkout master
> > git pull origin master
> > git checkout adding-sneak-animation
> > git rebase master
> > 
> > yarn test
> > yarn test:lint
> > ```
> 
> where it says "git checkout adding-sneak-animation" should it be "git checkout add addToolbarButtons" ?

> > Can you run these commands and resolve all issues (tests and lint)?
> > And does mark buttons work as expected?
> > ```shell
> > git checkout master
> > git pull origin master
> > git checkout adding-sneak-animation
> > git rebase master
> > 
> > yarn test
> > yarn test:lint
> > ```
> 
> where it says "git checkout adding-sneak-animation" should it be "git checkout add addToolbarButtons" ?

You are right. Can you rebase from master and fix all lint issues?

2020-09-21 19:47 UTC, qmfkdldks approved these changes
Thank you
Have you checked if the buttons work fine? (whether it change the text with the corresponding element)
Should check `src/components/Leaf`

2020-09-22 19:46 UTC, merged